name: airlib
description: A peer to peer file transfer library
version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  uuid: ^2.0.2
  dio: ^3.0.9
  meta: ^1.1.8
  filesize: ^1.0.4
  emodebug:
  path: ^1.6.4
  csv: ^4.0.3
  nodecommander:
    path: ../nodecommander
